#pragma once
// Generated by TinyPanel Studio. Edit hardware.json or use Hardware Setup.
#define TP_CONTROLLER_ESP32_C3_SUPER_MINI 1
#define TP_DISPLAY_ST7735 1
#define TP_BUS_HARDWARE_SPI 1
#define TP_TFT_WIDTH 160
#define TP_TFT_HEIGHT 128
#define TP_TFT_ROTATION 3
#define TP_COLOR_ORDER_RGB 1
#define TP_SPI_FREQUENCY 40000000
#define TP_SERVER_HOST "192.170.60.234"
#define TP_SERVER_PORT 8765
#define TP_TFT_CS 0
#define TP_TFT_DC 3
#define TP_TFT_RST 4
#define TP_TFT_MOSI 2
#define TP_TFT_SCLK 1
#define TP_TFT_MISO -1
#define TP_TFT_BACKLIGHT -1
